- File: Im2ColMaxPool.cu
  Kernels:
   - im2col_kernel
   - MaxPoolForward
- File: Im2ColNormalization.cu
  Kernels:
   - im2col_kernel
   - batch_norm_collect_statistics_kernel
- File: SummaryOps.cu
  Kernels:
   - im2col_kernel
   - kernelHistogram1D
- File: Im2ColUpSample.cu
  Kernels:
  - im2col_kernel
  - upsample_bilinear2d_out_frame
- File: MaxPoolBatchNorm.cu
  Kernels:
   - MaxPoolForward
   - batch_norm_collect_statistics_kernel
- File: MaxPoolUpSample.cu
  Kernels:
    - MaxPoolForward
    - upsample_bilinear2d_out_frame
- File: SummaryMaxpool.cu
  Kernels:
    - kernelHistogram1D
    - MaxPoolForward
- File: SummaryUpsample.cu
  Kernels:
    - kernelHistogram1D
    - upsample_bilinear2d_out_frame
- File: UpsampleNormalization.cu
  Kernels:
    - upsample_bilinear2d_out_frame
    - batch_norm_collect_statistics_kernel
- File: SummaryNorm.cu
  Kernels:
    - kernelHistogram1D
    - batch_norm_collect_statistics_kernel
